### ISSUE TITLE
Opening project hangs on loading (Socket.io and anti virus?)

### ISSUE THREAD

**Issue by hkinks** [sharelatex/sharelatex-docker-image#10]
Hi,

I have installed sharelatex using docker and everything works fine, except on the machines that have for example TrendMicro OfficeScan installed. On those machines opening projects hangs on loading screen. Javascript console output can be seen on the attached image.
![eb244b](https://cloud.githubusercontent.com/assets/1926790/7319234/a1e82092-ea9c-11e4-997a-3c5503070199.png)

I assume the problem occurs because of socket.io being blocked by anti virus, however on sharelatex.com everything works. So, I wonder what could be the difference. Also when I run  on port 3000 for example, then again, it seems to work.

Is there any workaround to this?

**Comment by henryoswald** [comment]
I am not too sure sorry, anti virus can be a strange beast, they often don't like websockets. Hope you work out a solution.
