### ISSUE TITLE
How to migrate server?

### ISSUE THREAD

**Issue by crockeea** [sharelatex/sharelatex-docker-image#101]
I have a dockerized ShareLaTeX server and would like to move it to a new server. 

[These](https://github.com/overleaf/overleaf/wiki/Database-migrations) directions do not help, and it isn't clear what https://github.com/overleaf/overleaf/tree/master/migrations is used for.

My first attempt was to `docker commit` the mongo container, upload it to a registry and download it again. This doesn't work because apparently mongo implicitly uses a docker volume. 

Next attempt was to manually export the database using this:
```
docker exec $OLD_CONTAINER bash -c 'mongodump --gzip --archive=/tmp/my_db.dump'
docker cp $OLD_CONTAINER:/tmp/my_db.dump mongo.db
docker cp mongo.db $NEW_CONTAINER:/tmp/my_db.dump
rm mongo.db
docker exec $NEW_CONTAINER bash -c 'mongorestore --gzip --archive=/tmp/my_db.dump'
```

But this results in errors:
```
2019-05-10T18:08:48.534+0000    error: multiple errors in bulk operation:
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "1_move_doc_lines_to_doc_collection" }
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "2_doc_lines_delete_from_project" }
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "3_pack_docHistory_collection" }
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "4_update_user_features" }
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "5_remove_holding_accounts" }
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "6_add_track_changes_feature" }
  - E11000 duplicate key error collection: sharelatex._migrations index: _id_ dup key: { : "7_add_track_changes_feature_again" }
```
These look suspiciously like the files in https://github.com/overleaf/overleaf/tree/master/migrations, but I have no idea what that means. Any help is appreciated.

**Comment by bonanza123** [comment]
Migrate from where to where?

I have all my data (mongo, redis and sharelatex) also in volumes. The volumes are essentially folders ssomewherein `/var/lib/docker/volumes`. You should be able to create backups from there and copy them over to the new volumes.

**Comment by crockeea** [comment]
I'm trying to migrate from one machine to another.

I started the server by running:
```
$ docker run -d --name shareredis redis:latest
$ docker run -d --name sharemongo mongo:latest
 
$ docker run -d -P -p 5000:80 -v ~/sharelatex_data:/var/lib/sharelatex \
  --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex \
  --env SHARELATEX_REDIS_HOST=redis \
  --link sharemongo:mongo \
  --link shareredis:redis \
  ....

$ sudo ls /var/lib/docker/volumes
metadata.db
```

I've mounted the ShareLaTeX data volume locally, so I know where to find that data. If mongo has data, I'm not sure where to find it. It doesn't appear to be in `var/lib/docker/volumes`.

**Comment by prohde** [comment]
If you still have problems with migrating to another server, please read my comment. Otherwise, please close the issue.


What is the output of the command `docker inspect sharemongo`? The part 'mounts' should help you to find the path to the volume(s).

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
