### ISSUE TITLE
Missing directory `modules`

### ISSUE THREAD

**Issue by kevinyen-oath** [sharelatex/sharelatex-docker-image#104]
There's a `cd modules` in the Dockerfile
https://github.com/overleaf/docker-image/blob/3c4866a/Dockerfile#L36

However, the directory `modules` was removed from repo `web`, https://github.com/overleaf/web/commit/71a00eee1e175d880cbfd974c7a93ffb60dcb820#diff-0eb9b3af2e4a00837a1b1a854c9ea18c, and this breaks the image building.

```
cd: modules: No such file or directory
```

**Comment by mserranom** [comment]
This is fixed now.
