### ISSUE TITLE
not able to create users and errors in web.log

### ISSUE THREAD

**Issue by marcodussin** [sharelatex/sharelatex-docker-image#12]
Hi
i'm not able to create users (emails are not sent, if i use the provided link it doesn't work) and i've got that error on my web.log.

Are these issues related to the same problem?

Exception: Error: failed to connect to [dockerhost:27017]
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
  at [object Object].emit (events.js:106:17)
  at [object Object].<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
  at [object Object].emit (events.js:98:17)
  at Socket.<anonymous> (/var/www/sharelatex/web/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
  at Socket.emit (events.js:95:17)
  at net.js:441:14
  at process._tickDomainCallback (node.js:492:13)

**Comment by henryoswald** [comment]
it looks like it can not talk to mongodb.

**Comment by marcodussin** [comment]
Yes, but what should i check? I'm a docker newbie...

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.14&pv=5.1]

On lun, mag 11, 2015 at 6:18 PM, Henry Oswald < notifications@github.com [notifications@github.com] > wrote:
it looks like it can not talk to mongodb.

—
Reply to this email directly or view it on GitHub
[https://github.com/sharelatex/sharelatex-docker-image/issues/12#issuecomment-100966589] .[https://github.com/notifications/beacon/ADxplP39xm5wEuvtoU8TtfWKd3jpyd--ks5oIM3WgaJpZM4EWXib.gif]

**Comment by mickaelbaron** [comment]
Hi,

If you have 3 containers: MongoDB, Reddis and Sharelatex, you need to link the containers of MongoDB and Reddis with the Sharelatex one.

For example my config.

```
$ docker run --name mongodb -v /var/mongodb:/data/db -d mymongodb
$ docker run --name redis -v /var/redis:/var/lib/redis -d myredis
$ docker run -d -v /var/sharelatex:/var/lib/sharelatex -p 80:80 --link redis:redis --link mongodb:mongodb --name=sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongodb/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_SITE_URL=http://yourdomain mysharelatex
```

Replace http://yourdomain by the domain or ip of your server, it's for socket.io.

An other solution is to use Docker compose ...

Mickael
