### ISSUE TITLE
Configure nginx to add both SSL and basic authentification supports

### ISSUE THREAD

**Issue by mickaelbaron** [sharelatex/sharelatex-docker-image#13]
Hi,

I would like to add both SSL support and basic authentication into my ShareLatex docker container.

Here is my sharelatex.conf with modifications to support SSL and basic authentication.

```
        listen         443;
        server_name    localhost; 

        ssl on;
        ssl_certificate /etc/nginx/ssl/localhost.crt;
        ssl_certificate_key /etc/nginx/ssl/localhost.key;

        set $static_path /var/www/sharelatex/web/public;

        location / {
                auth_basic "You need to log in";
                auth_basic_user_file /etc/nginx/htpasswd/sharelatex.passwd;
                proxy_pass http://localhost:3000;
                ...
        }
...
```

SSL support is working, but when i want to add a basic authentication is not working.

Do you think my configuration is ok ?

Any idea about my problem ?

Thanks

Mickael

**Comment by henryoswald** [comment]
try moving auth_basic up a level  outside of location /
