### ISSUE TITLE
Setup mail when using docker image

### ISSUE THREAD

**Issue by bajo** [sharelatex/sharelatex-docker-image#19]
Hi, 

I installed the docker image according the the instructions given on https://github.com/sharelatex/sharelatex-docker-image, but it does not seem able to send out any emails from within the docker container. 
Maybe i missed the hint on how to configure the outgoing mail connection. Can somebody with a little more insight point me to the instructions that apply to the docker version of sharelatex?

Thanks.
bajo

**Comment by ghost** [comment]
I have the same question
Any other help will be REALLY appreciated!
Thank you guys

**Comment by henryoswald** [comment]
what type of email setup are you using?

**Comment by ghost** [comment]
I want to send email from the server which I installed this sharelatex, but did not know how to config.  I have't  install anything without this image docker . Thank you

**Comment by bajo** [comment]
@henryoswald Same for me as for @tiendv1 . 
I installed the docker image following the instructions, but could not figure out where or how to configure the settings so that sharelatex is able to send emails. This is especially annoying when trying to add ne users. 
Any hints are welcome. :)

**Comment by henryoswald** [comment]
The example config is the best place to look

https://github.com/sharelatex/web-sharelatex/blob/master/config/settings.defaults.coffee#L183

On Tue, Dec 22, 2015 at 8:38 AM, Markus Bajones notifications@github.com
wrote:

> @henryoswald https://github.com/henryoswald Same for me as for @tiendv1
> https://github.com/tiendv1 .
> I installed the docker image following the instructions, but could not
> figure out where or how to configure the settings so that sharelatex is
> able to send emails. This is especially annoying when trying to add ne
> users.
> Any hints are welcome. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sharelatex/sharelatex-docker-image/issues/19#issuecomment-166553712
> .

## 

Henry Oswald
shareLaTeX.com co-founder

**Comment by frederikcreemers** [comment]
Yes, I've found that configuration file, and I've located where inside docker's filesystem it is located, but editing files directly on the "union" filesystem is not a good idea. So maybe it would be a good idea to make this configurable via environment variables as well.

**Comment by bajo** [comment]
@henryoswald @bigblind So we are still at the point where it is not easily possible to setup the mail system when sharelatex is in a docker container? If I change the settings in the docker container, how would I be able to store them permanently? I guess that sharelatex needs some kind of restart to load the new settings. 
The idea to store such settings in environment variable sounds great.

**Comment by henryoswald** [comment]
Hi, yes its on the todo list to make these env variables.

sent from my phone.

**Comment by bajo** [comment]
Great, thank you. 
Is there any way we could help with this part of the todo list?

**Comment by appelgriebsch** [comment]
Just stumbled over the same issue... looks like you have to go to the running container via 

``` bash
docker exec -it sharelatex bash
```

and work on the settings in /etc/sharelatex/settings.coffee following this guide https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email

**Comment by mlopezantequera** [comment]
Do these changes to settings.coffee remain after restarting the container? If not, how can they be saved?

**Comment by frederikcreemers** [comment]
You could make a new image derived from this one which overwrites the
settings file.

**Comment by mlopezantequera** [comment]
Thanks @bigblind , I imagine the steps are:
1. run bash in the container, edit settings.coffee to setup email
2. restart sharelatex within the container so the settings are loaded
3. make a new image

But I'm not sure how to proceed for step 2. Any ideas? Thanks

**Comment by alexbog8** [comment]
I managed to make it work from inside the container. Here are the steps: 
1. Launch the docker image, now you should be able to access the sharelatex to http://localhost:5000 for example. 
2. Enter the docker image with 
   `docker exec -it sharelatex bash`
3. Edit the /etc/sharelatex/settings.coffee by adding the correct settings in the e-mail section (I addedd fromAddress, replyTo, trasnport SMTP, host and port)
4. exit the docker image. Now with the new setting you should create a new docker image with the command:
   `sudo docker commit -m "your comments" CONTAINER ID (you get it with docker ps) sharelatex/sharelatex:v2` for example mine was
   `sudo docker commit -m "smtp settings" 2bd0ee390f0c sharelatex/sharelatex:v3`
5. Stop and remove the current docker:
   `docker stop sharelatex` and `docker rm sharelatex`
6. Start the new docker image, for instance
   `sudo docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex   -p 5000:80   --name=sharelatex   sharelatex/sharelatex:v3`
7. Enjoy email sending from inside docker

**Comment by PandaScience** [comment]
Hi. @alexbog8 Could you please tell a bit more about step 3?
I'm currently also trying to setup email from within the docker container but it's not working.

Do you have installed the MTA in the container or on the host configured as satellite or are you using a smarthost like e.g. smtp.gmail.com directly?

Which of the config files did you edit exactly, `/etc/sharelatex/settings.coffee` or `/var/www/sharelatex/web/config/settings.defaults.coffee`? Changes in the first one don't have any affect. When editing the second one to use "localhost" port 25 as worked for me in sharelatex v0.1.4, I get an ECONNREFUSED from nodemailer. 

Any suggestions?

**Comment by alexbog8** [comment]
You need to edit the file at /etc/sharelatex/setting.coffee ! For the host I used my usual outgoing server given by my ISP! Yes smtp.gmail.com should work as well !

**Comment by gustavokcouto** [comment]
# You must configure a mail server to be able to send invite emails from
    # ShareLaTeX. The config settings are passed to nodemailer. See the nodemailer
    # documentation for available options:
    #
    #     http://www.nodemailer.com/docs/transports
    
    
    
    settings.email =
            fromAddress: 'user@gmail.com'
            replyTo: 'user@gmail.com'
            parameters:
                    #AWS Creds
                    AWSAccessKeyID: process.env["SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID"]
                    AWSSecretKey: process.env["SHARELATEX_EMAIL_AWS_SES_SECRET_KEY"]
    
                    #SMTP Creds
                    host: 'smtp.gmail.com',
                    port: 465,
                    secure: true,
                    ignoreTLS: false
    
            textEncoding:  process.env["SHARELATEX_EMAIL_TEXT_ENCODING"]
            templates:
                    customFooter: process.env["SHARELATEX_CUSTOM_EMAIL_FOOTER"]
    
    settings.email.parameters.auth =
            user: 'user@gmail.com',
            pass: 'gmail_password'
    
    settings.email.parameters.tls =
            rejectUnauthorized: true
    
    # i18n
    if process.env["SHARELATEX_LANG_DOMAIN_MAPPING"]?
    
            settings.i18n.subdomainLang = parse(process.env["SHARELATEX_LANG_DOMAIN_MAPPING"])

**Comment by henryoswald** [comment]
Hi,

you should ideally not change settings.coffee, use the env vars instead https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email

**Comment by gustavokcouto** [comment]
Would help a lot if had an example to configure a common mail server like gmail using the env vars. I tried a lot using the docker-compose.yml to set the variables but with no success

**Comment by jwynn6** [comment]
I too cannot get the docker-compose.yml to work.  A gmail example would go a long way to ensuring ease of set up.

**Comment by d0uwe** [comment]
I can not get mail to work either after filling the env vars in docker-compose.yml. I installed a mail server on both the docker instance and the host instance, but neither receive a request to send a mail. The log in /var/log/sharelatex/web.log keeps saying the SMTP connection timed out.

**Comment by arjunsuresh** [comment]
Me too. I'm getting. 
level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n    at errnoException (net.js:905:11)\n    at Object.afterConnect [as oncomplete] (net.js:896:19)\n","code":"ECONNREFUSED"},"msg":"error sending message","time":"2017-05-16T06:26:39.084Z","v":0}

Tried with my mail server as well as gmail.

**Comment by d0uwe** [comment]
`            
as variables i passed the following in the docker compose file: 
SHARELATEX_EMAIL_FROM_ADDRESS: mygmail@gmail.com

            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID: 
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY: 

            SHARELATEX_EMAIL_SMTP_HOST: smtp.gmail.com
            SHARELATEX_EMAIL_SMTP_PORT: 465
            SHARELATEX_EMAIL_SMTP_SECURE: 'true'
            SHARELATEX_EMAIL_SMTP_USER: mygmail@gmail.com
            SHARELATEX_EMAIL_SMTP_PASS: mypassword
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: 'false' 
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"`

Could anyone perhaps provide feedback why that would not work?

**Comment by arjunsuresh** [comment]
@douwe What error you see in /var/log/sharelatex/web.log after logging to sharelatex docker bash?

**Comment by d0uwe** [comment]
@arjunsuresh
`{"name":"web-sharelatex","hostname":"3b1985dc1d7e","pid":94,"level":50,"err":{"message":"Connection timeout","name":"Error","stack":"Error: Connection timeout\n    at SMTPConnection._formatError (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:424:15)\n    at SMTPConnection._onError (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:410:16)\n    at SMTPConnection.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:178:14)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)\n","code":"ETIMEDOUT"},"msg":"error sending message","time":"2017-05-17T17:50:25.260Z","v":0}`

**Comment by arjunsuresh** [comment]
"format error" - may be some typo. I did not use the compose yml file and passed the parameters directly in terminal. Here is the command I used with an SMTP server supporting only TLS auth on port 465. For Gmail, there might be an additional security check which might need additional measures -- will show in the same log file. 

sudo docker run -d   -v ~/sharelatex_data:/var/lib/sharelatex --env SHARELATEX_EMAIL_FROM_ADDRESS="gatecse@gateoverflow.in" --env SHARELATEX_EMAIL_REPLY_TO="gatecse@gateoverflow.in" --env SHARELATEX_EMAIL_SMTP_HOST="mail.gatecse.in" --env SHARELATEX_EMAIL_SMTP_PORT=465 --env SHARELATEX_EMAIL_SMTP_SECURE=true --env SHARELATEX_EMAIL_SMTP_USER="admin" --env SHARELATEX_EMAIL_SMTP_PASS="" --env SHARELATEX_EMAIL_SMTP_IGNORE_TLS=false --env SHARELATEX_SITE_URL="http://mysite.com" --env SHARELATEX_NAV_TITLE="GO ShareLaTeX Instance" --env SHARELATEX_ADMIN_EMAIL="support@gateoverflow.in"  -p 80:80   --name=sharelatex   sharelatex/sharelatex

**Comment by d0uwe** [comment]
Hey, thanks for your help and you are probably right. In the default docker-compose file some examples are given such as that a boolean should be passed as simply: true. Sadly this does not get accepted, and i tried a lot of things such as "true" or 1. Probably this is the reason for the format error, which is kind of unrelated to this issue, so i'll open a new issue for that. 

The command you gave only starts a dead instance for me, it doesn't do anything or cause any processor usage, where the docker compose version gives me quite a startup time.

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
so is there anyone can setup email notification?  If you make, could you give me docker compose file demo?

**Comment by EadrenKing** [comment]
# When sending email, some error in web.log

{"name":"web-sharelatex","hostname":"44164bdbb00f","pid":117,"level":50,"err":{"message":"unable to verify the first certificate","name":"Error","stack":"Error: unable to verify the first certificate\n  at Error (native)\n  at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)\n  at emitNone (events.js:86:13)\n  at TLSSocket.emit (events.js:185:7)\n  at TLSSocket._finishInit (_tls_wrap.js:610:8)\n  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)\n","code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"msg":"error sending message","time":"2018-01-29T07:51:30.656Z","v":0}


{"name":"web-sharelatex","hostname":"44164bdbb00f","pid":117,"level":50,"err":{"message":"Cannot send email","name":"Error","stack":"Error: Cannot send email\n  at /var/www/sharelatex/web/app/js/Features/Email/EmailSender.js:126:19\n  at Nodemailer.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer/lib/nodemailer.js:213:26)\n  at SMTPConnection.<anonymous> (/var/www/sharelatex/web/node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:80:16)\n  at SMTPConnection.g (events.js:292:16)\n  at emitOne (events.js:96:13)\n  at SMTPConnection.emit (events.js:188:7)\n  at SMTPConnection._onError (/var/www/sharelatex/web/node_modules/smtp-connection/lib/smtp-connection.js:414:10)\n  at emitOne (events.js:96:13)\n  at TLSSocket.emit (events.js:188:7)\n  at emitErrorNT (net.js:1281:8)\n  at _combinedTickCallback (internal/process/next_tick.js:80:11)\n  at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n"},"url":"/launchpad/send_test_email","method":"POST","user":{"id":"5a6ed24e7455a90075aa7b46","email":"jinyejun@ncic.ac.cn"},"msg":"error passed to top level next middlewear","time":"2018-01-29T07:51:30.658Z","v":0}


{"name":"web-sharelatex","hostname":"71f340ee262a","pid":119,"level":50,"err":{"message":"unable to verify the first certificate","name":"Error","stack":"Error: unable to verify the first certificate\n  at Error (native)\n  at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)\n  at emitNone (events.js:86:13)\n  at TLSSocket.emit (events.js:185:7)\n  at TLSSocket._finishInit (_tls_wrap.js:610:8)\n  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)\n","code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"},"msg":"error sending message","time":"2018-01-29T08:18:54.168Z","v":0}

**Comment by fanggeyishui** [comment]
could anyone help me?I  make all the configuration followed the doc https://github.com/sharelatex/sharelatex/wiki/Configuring-SMTP-Email,  but it didn't work at all. When  I get register page,there is only 'contact admin to create an account'.  I try all the method above,such like edit setting.coffe in the docker,pass parameters directly in teminals,but it didn't work.
So much thanks!

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
