### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by sennierer** [sharelatex/sharelatex-docker-image#2]
When trying to install share latex via docker I get a 502 error from nginx.
I use the command as suggested: 
docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --name=sharelatex \
  sharelatex/sharelatex

As I am also running an apache server on the same machine I guess nginx included in the docker image is listening on port 80 and not 5000...

**Comment by marcodussin** [comment]
same error :-1:

**Comment by Valantin** [comment]
Hi, I've docker 1.3.3 on debian 8, run the container using "docker run -d -v /opt/sharelatex/:/var/lib/sharelatex --name=sharelatex -p 80:80 sharelatex/sharelatex", also with the command suggested in the readme and I have same issue.
What error you talking about?

**Comment by marcodussin** [comment]
What i was saying is that I have the same error/issue...

**Comment by Valantin** [comment]
@marcodussin sorry, my misunderstanding

**Comment by eingrossfilou** [comment]
I got the same error when I pull the docker image or build it. However, I think the 502 error is not related to a port problem but to a problem with the nodejs service: when I launch the sharelatex docker container, I observe that nodejs consume 100% of my cpu time. IMHO I think the 502 error come from the fact that nodejs do not answer to requests.

Updating the system and sharelatex in the docker image do not solve the problem.

Edit: tests were done with docker 1.5.0 under debian 7.8 with backported kernel from wheezy-backport.

**Comment by pgampe** [comment]
Same here.  Using docker with Fedora 21. 

```
 nginx/1.4.6 (Ubuntu) just responds with 502 Bad Gateway
```

**Comment by gueraf** [comment]
Same here with utopic and docker 1.5.0. All 10 node processes seem to run and web.log says "web-sharelatex listening on port 3000" (i.e. it doesn't crash because it can't connect to the mongodb). 

Hope somebody can look into this.

**Comment by marcodussin** [comment]
It seems sharelatex team is ignoring us...

**Comment by ukasiu** [comment]
same here.

**Comment by moosetraveller** [comment]
dito

**Comment by Nobody84** [comment]
same here:

**Host:** 
Debian 7.8

**Docker version:**
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

**Comment by Nobody84** [comment]
I recognized that mongodb-server and redis-server were not installed on the host.

Install the mongodb and redis as described here [https://github.com/sharelatex/sharelatex/wiki/Dependencies]
and changing the conifg as described here [https://github.com/sharelatex/sharelatex-docker-image#mongo-and-redis] solved the problem for me.

**Comment by Valantin** [comment]
Hi, using @Nobody84's information, I've run
$ docker run -d --name sharemongo mongo:latest
$ docker run -d --name shareredis redis:latest
$ docker run -d -P -p 80:80 -v /opt/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --end SHARELATEX_REDIS_HOST=redis --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex
and it seems to work

**Comment by redfern314** [comment]
Correction to @Valantin's (very helpful!) comment: --end should be --env in the last command. Fixed command below.

$ docker run -d -P -p 80:80 -v /opt/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex

**Comment by marcodussin** [comment]
it works for me too. ATTENTION: if you have troubles with mongo drivers (e.t. on ubuntu) refer to https://github.com/sharelatex/sharelatex-docker-image/issues/7 and install mongo using  
$ docker run -d --name sharemongo mongo:2.6.9

**Comment by 84matte84** [comment]
Hi guys...I have tried all your suggestions, but none of them worked for me. I am on Fedora 22 server and I have followed the instructions from @Valantin in the exact order but nothing...I am still having the Error 502

Any other help will be REALLY appreciated!
Thank you guys

**Comment by henryoswald** [comment]
Hey, if you look in side the docker container at /var/log/sharelatex is there anything interesting in the logs?

**Comment by 84matte84** [comment]
Hi @henryoswald ...  sadly I have found the following erros:

./web.log:Exception: Error: failed to connect to [mongo:27017]
./document-updater.log:Error: Redis connection to redis:6379 failed - connect EHOSTUNREACH
./real-time.log:Error: Redis connection to redis:6379 failed - connect EHOSTUNREACH

but I am not able to fix them...any hint? :D

**Comment by henryoswald** [comment]
It looks like the docker container can not see wherever you are pointing mongodb/redis, are you sure your SHARELATEX_MONGO_URL etc are correct?

**Comment by 84matte84** [comment]
I have just copy/paste what I found in this page....this is my first run with docker...how can I check them? and what do they point to?

thanks for your help!

**Comment by henryoswald** [comment]
Do you have your own instance of mongodb and redis running? This isn't todo
with docker at this point if they are not yet running locally. If you go
through https://github.com/sharelatex/sharelatex-docker-image it should
explain how you need to set them up. You can check they are live by trying
to access them via the standard command line tools like redis-cli and mongo

On Thu, Jul 30, 2015 at 11:15 PM, 84matte84 notifications@github.com
wrote:

> I have just copy/paste what I found in this page....this is my first run
> with docker...how can I check them? and what do they point to?
> 
> thanks for your help!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sharelatex/sharelatex-docker-image/issues/2#issuecomment-126507679
> .

## 

Henry Oswald
shareLaTeX.com co-founder

**Comment by pgampe** [comment]
Have you checked your firewall settings? Fedora 22 comes with firewalld enabled, including some rules for all interfaces, especially blocking connections from the "outside".

**Comment by 84matte84** [comment]
Sorry for the late reply....I tried both your hints but still I am having the Error 502 when trying to open sharelatex from another pc in the same LAN...

this is the situation:

1)I have used "dockerhost" as written in the manual and also used the right container names to link them correctly from sharelatex container and now my log directory has no errors:

root@aa853970c089:/# grep -Ri error /var/log/sharelatex/

Furthermore I have checked the iptables and what should be there seems to be there as following:

sudo iptables -L -n -t nat | grep -i docker
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
Chain DOCKER (2 references)

But still I cannot access sharelatex...what should I do/check next?

Thank you for your help!

**Comment by ghost** [comment]
On CentOS 7.0 we originally had this problem as we did not have mongodb or redis installed.
Installed mongodb according to the instructions here : http://docs.mongodb.org/manual/tutorial/install-mongodb-on-red-hat/
Note that you must copy the /etc/mongod.conf.rpm.new over to /etc/mongod.conf and change the bindIP parameter to what it is in the sharelatex docker install [the ip of the docker0 interface]
Redis was simply installed via yum, change the bind parameter as in the docs. [the ip of the docker0 interface]
After that I was able to restart sharelatex [docker restart sharelatex] and everything worked perfectly.

Let me suggest that the installation instructions should have the installation of mongodb and redis BEFORE the docker command to start the sharelatex image. It is really a prerequisite for the docker installation to work, so it logically should be put before the step of pulling the image and running the instance. I think many users would be confused by the current description as it sort of implies that you can run sharelatex without them.

**Comment by benoitldr** [comment]
here the solution which works for me
`sudo docker run -d --name sharemongo -v /var/mongodb:/data/db mongo:2.6`
`sudo docker run -d --name shareredis -v /var/redis:/var/lib/redis redis:latest`
`sudo docker run -d -P -p 5000:80 -v /var/sharelatex:/var/lib/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_ADMIN_EMAIL=admin@blandrieu.fr --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex`

and 

`sudo docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email admin@blandrieu.fr"`

thanks to @Valantin @marcodussin

**Comment by 062bel313** [comment]
Hi everyone, i also used exactly same as @benoitldr did (just changed 5000 to 5050 and volume shares). Now i can access the web page of share latex, create accounts but LaTeX throws me error that:

"Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments."

Also if i try to upload my files (as .zip) it does not upload rather asks if its a correct zip file?
Can anybody help me. If you need some logs i can provide it. I am not sure where to look at. There is also another tread open, but no answers yet. Since i used the method you guys mentioned i thought i could get a quick help.
 I will also post this message to that thread. or you can help me in that thread
I am a beginner and using docker for first time. Thank you!

**Comment by 062bel313** [comment]
I think i figure it out. It is about the permissions to the folders of mongo, share latex and redis. For now i have given read/write permission to everyone and it is working fine. I will change the permission till it works.

**Comment by ghost** [comment]
Still not working for me, unfortunately. I followed all the steps as described by @benoitldr, changed 5000 to 4050 as well as the volume paths. But when I enter the create-admin-user task, i get: 
`Running "create-admin-user" task`
`Fatal error: driver is incompatible with this server version`
If I go to http://mylocalip:4050/, I still get 502 Bad Gateway

I'm running this on a NAS by Synology - does anyone have a suggestion? Thx!

**Comment by 062bel313** [comment]
Ok i think you are using latest version of mongodb:latest or higher than 2.6.x. Use version 2.6 It will work. I was getting the same issue, installed ver 2.6 and it worked. Try that.

**Comment by MiauWuffMiau** [comment]
Thanks to @benoitldr for your instructions. 

For those that also struggled with mongos official MongoDB 2.6 Docker container image. I struggled over this issue: 

"2016-04-15T10:20:46.596+0000 [initandlisten] exception in initAndListen: 28574 Cannot start server. Detected data files in /data/db created by storage engine 'wiredTiger'. The configured storage engine is 'mmapv1'., terminating"

**The solution that works for me (Most probably get rid off the resources stuff):**
**MongoDB** (if you need auth, definitively change it!)
`docker run -d --name sharemongo --cpuset-cpus=5 -m 2048m -e AUTH=no tutum/mongodb`

**Redis**
`docker run -d --name shareredis --cpuset-cpus=6 -m 2048m -v /var/redis:/var/lib/redis redis`

**Sharelatex**
`docker run -d --cpuset-cpus=2,3 -m 4096m -P -p 5000:80 -v /var/sharelatex_data:/var/lib/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_ADMIN_EMAIL=miau@lets-hack.it --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex`

**Setting up admin**
`docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email miau@lets-hack.it"`

Cheers,
Miau

**Comment by MarcoMeter** [comment]
@Valantin @marcodussin @benoitldr  based on your instructions, did you manage to launch sharelatex on system start up?

Adding the parameters _--restart always_ during the _docker run_ command breakes the container (container can't be started at all). I also tried these steps https://docs.docker.com/engine/admin/host_integration/

**Comment by snazzybunny** [comment]
@MarcoMeter I tried that link but keep getting "Error response from daemon: Cannot link to a non running container: /sharemongo AS /sharelatex/mongo". How do you guys make sharelatex autostart on reboot? Thanks. I think I need to figure out how to start sharemongo and shareredis to start before sharelatex.

**Comment by MarcoMeter** [comment]
After changing the IP of the Docker Bridge, I'm facing again the 502 issue. I had to change the IP due to access issues (after installing docker access within the intranet didn't work while access from the internet was working). 

So I tried to bind Mongo and Redis to the IP of the Network Bridge using their respective configs without any success. Any ideas?

Edit:

I originally set the IP of docker to something like 10.177.11.12/24. So the first docker container would use 10.177.11.1 as ip adress which conflicts with the gateway of my subnet, so I gave docker a different one like 10.177.111.1/24. Now everything seems to work accordingly.

Edit 2:

I didn't work on the restart issue, yet.

**Comment by henryoswald** [comment]
This is a bit of a dumping ground of random errors so closing for moment to keep on top of things. There is a new docker image available now with better logging that should help problems.

**Comment by MartinThoma** [comment]
```
$ git clone https://github.com/sharelatex/sharelatex
$ cd sharelatex
$ sudo docker-compose up
```

If you have something at port 80 running, change the `docker-compose.yml` from

```
        ports:
            - 80:80
```

to

```
        ports:
            - 5123:80
```

(if 5123 is free - the right 80 is the port within the container, the left 80 is the port on the host)

Then go to http://localhost:5123/launchpad to create the admin account.

Then execute the following two commands to update to full LaTeX.

```
$ sudo docker exec sharelatex tlmgr update --self
$ sudo docker exec sharelatex tlmgr install scheme-full
```
