### ISSUE TITLE
Upload File Size

### ISSUE THREAD

**Issue by jazzdd86** [sharelatex/sharelatex-docker-image#20]
I cannot upload files bigger than 1024KB! How can I change that in a short term? Images are often bigger than 1MB.
Please make the max upload size configurable.

**Comment by henryoswald** [comment]
Have you got some sort of reverse proxy in front like nginx, it will be that which is blocking it.

**Comment by jazzdd86** [comment]
Ah ok, yes I have nginx as reverse proxy. What you mean is, it is not possible to use a reverse proxy with sharelatex? Or does it just need to be configured in the right way

**Comment by henryoswald** [comment]
You need to configure nginx to not limit it. Have a google about
for ShareLaTeX nginx configs and you will find examples.

On Thu, Oct 22, 2015 at 9:17 PM, jazzdd86 notifications@github.com wrote:

> Ah ok, yes I have nginx as reverse proxy. What you mean is, it is not
> possible to use a reverse proxy with sharelatex? Or does it just need to be
> configured in the right way
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sharelatex/sharelatex-docker-image/issues/20#issuecomment-150344302
> .

## 

Henry Oswald
shareLaTeX.com co-founder

**Comment by jazzdd86** [comment]
Actually, it wasn't my nginx proxy causing the problem.
It was the nginx proxy build into the docker image.
file /etc/nginx/sites-enabled/sharelatex.conf was missing the client_max_body_size line completely.
