### ISSUE TITLE
/var/www/sharelatex/web doesn't exist

### ISSUE THREAD

**Issue by apetros** [sharelatex/sharelatex-docker-image#21]
Hi, I followed the instructions as shown in the wiki and the sharelatex is up and running and can be accessed remotely. However, when I try to create the admin account:

``` bash
docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email joe@example.com"
```

I get:

``` bash
/bin/bash: line 0: cd: /var/www/sharelatex/web: No such file or directory
```

When I run:

``` bash
docker exec sharelatex /bin/bash -c "ls /var/www/"
```

I get:

``` bash
css
index.html
js
mydropbox
nginx-default
sample_page.html
widget_schedule.html
widgets.html
```

Anyone can help me? It's frustrating... It's like I'm almost there, but I lost the key...

``` bash
>docker info
Containers: 1
Images: 52
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
```

**Comment by KaleoCheng** [comment]
Me too. And I have even no grunt.
```shell
/bin/bash: line 0: cd: /var/www/sharelatex/web: No such file or directory
/bin/bash: grunt: command not found
```
I also on Debian 7:

```shell
>docker info
Containers: 4
Images: 101
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 109
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
```

**Comment by kaleocheng** [comment]
I think this is the Docker Bug on Debian 7 , in fact, you access the host 's file instead of Docker container.

**Comment by kaleocheng** [comment]
@p3tris Use Debian 8,then it works!

**Comment by apetros** [comment]
Thanks. I've been wanting to upgrade for some time now. I'll let you know.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
