### ISSUE TITLE
nginx intermittent failures if IPv6 not enabled on the machine

### ISSUE THREAD

**Issue by Micket** [sharelatex/sharelatex-docker-image#26]
I experienced intermittent failures of the nginx server using the docker image on a RHEL7.1 virtual machine. Every second refresh led to "internal server error 500". 

Seems this was due to IPv6 not being enabled on the machine. It was solvable through switching out "localhost" to IPv4 address "127.0.0.1" inside the docker image nginx conf.
Otherwise it was resolved to [::1] which was not understood by nginx (logs print "socket() failed (address family not supported by protocol)").

I'm no expert, but perhaps it's better to just use this IPv4 address from the start?

**Comment by numbleroot** [comment]
We had the same problem today. @Micket's suggestion to change `localhost` to `127.0.0.1` inside the `location` blocks in `sharelatex-docker-image/nginx/sharelatex.conf` fixed it.

**Comment by henryoswald** [comment]
Hi,

I have committed a change to 127.0.0.1 so that will be the default for future builds.
