### ISSUE TITLE
issues with ssl

### ISSUE THREAD

**Issue by Xarin** [sharelatex/sharelatex-docker-image#29]
I have sharelatex up and running (when the firewalls are down you can get to the sharelatex services fine though port 5000) and I have a working instance of nginx on the host machine that is successfully using SSL. My only problem now is there seems to be an issue between the nginx communications within the docker container and the nginx instance i'm running on the host machine. 

I'm getting this error on the browser 
400 Bad Request

nginx/1.4.6 (Ubuntu)

and this error on the nginx service inside the container 
"2016/01/29 15:45:24 [error] 89#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://[::1]:3000/", host: "hostname.com:5000""

This is my host machine nginx sharelatex.conf file 
server {
    listen         443;
    server_name    _; # Catch all, see http://nginx.org/en/docs/http/server_names.html

```
ssl on;
ssl_certificate /etc/ssl/certs/cirt.crt;
ssl_certificate_key /etc/ssl/keys/key.key;
#set $static_path /var/www/sharelatex/web/public;

location / {
    proxy_pass http://localhost:5000;
    proxy_set_header Host $http_x_forwarded_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 3m;
    proxy_send_timeout 3m;
}

location /socket.io {
    proxy_pass http://localhost:3026;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_x_forwarded_host;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 3m;
    proxy_send_timeout 3m;
}
```

}

Any suggestions are welcome.
Thanks,

**Comment by henryoswald** [comment]
Hi, this guide will fix it for you https://github.com/sharelatex/sharelatex/wiki/HTTPS-reverse-proxy-using-Nginx
