### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by leandroqm** [sharelatex/sharelatex-docker-image#30]
Hello,

First, let me thank you for developing Sharelatex and releasing it as an open source project.
I really enjoy using the project and we used it for a paper we just submitted.

I am running sharelatex as a docker container, but I can't seem to figure out how to fix some language issues.
For the first paper, everything worked. The paper was in english, so there was no issues.
For the second paper (in brazilian portuguese), I am having all kinds of issues. :-)

For instance: 
"Departamento de Informática e Estatística"
becomes (when rendered and from files uploaded)
"Departamento de Inform�tica e Estat�stica",

latex seems to think that some words are math expressions ("Missing $ inserted"), etc.

I've tried two things so far:
1 - updating locales on the sharelatex docker OS (docker exec -it sharelatex /bin/bash and then updating ubuntu's locales with locale-gen "pt_BR.UTF-8" and dpkg-reconfigure locales).
2 - changing fontenc and inputenc on the document.

So far, no luck. :-)
Could anyone give me a hand?

Thank you.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
