### ISSUE TITLE
“Error opening document”when i open a project

### ISSUE THREAD

**Issue by sin-zx** [sharelatex/sharelatex-docker-image#36]
i have just finished the installation of docker image.
But when i open the project,it shows "Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments"
and the edition part in the left keep“loading...”
i guess it may be the problem of database,mongodb or redis.
because i met the problem before i successfully created a new admin user.It was the cause of mongo version.I run the mongodb of 3.0.And i solve it by "Go into /var/www/sharelatex/web and change the version of mongoose to 3.8.27 in your package.json and run npm install." ,which is the solution from [@ipsq](https://github.com/sharelatex/sharelatex-docker-image/issues/7)
So ,what can i do? Should i change re install the mongodb or redis?

**Comment by sin-zx** [comment]
@jpallen @henryoswald

**Comment by henryoswald** [comment]
Have you built the latex image?

**Comment by sin-zx** [comment]
Should i built the latex image?i don't know this case.please tell me how to do. @henryoswald 
I just run the "docker run -d -v ~/sharelatex_data:/var/lib/sharelatex -p 5000:80 --name=sharelatex \sharelatex/sharelatex" and install the sharelatex image
but then i have run the "docker exec sharelatex tlmgr install scheme-full" to install a scheme-full of TeXLive.Is this one?

**Comment by 062bel313** [comment]
I am having similar issue!

Hi everyone, i  used exactly same method as @benoitldr did (just changed 5000 to 5050 and volume shares). 

sudo docker run -d --name sharemongo -v /volume1/docker/mongodb:/data/db mongo:2.6
sudo docker run -d --name shareredis -v /volume1/docker/redis:/var/lib/redis redis:latest
sudo docker run -d -P -p 5000:80 -v /var/volume1/Share\ Latex:/var/lib/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --env SHARELATEX_ADMIN_EMAIL=admin email address --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex

and 

sudo docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email my email address"

Now i can access the web page of share latex, create accounts but LaTeX throws me error that:

"Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments."

Also if i try to upload my files (as .zip) it does not upload rather asks if its a correct zip file?
Can anybody help me. If you need some logs i can provide it. I am not sure where to look at. 

I am a beginner and using docker for first time. Thank you!

**Comment by 062bel313** [comment]
I think i figure it out. It is about the permissions to the folders of mongo, share latex and redis. For now i have given read/write permission to everyone and it is working fine. I will change the permission till it works.

**Comment by ghost** [comment]
any update on this?

**Comment by M-Gregoire** [comment]
I'm having this exact problem. I tried building the docker image from the Dockerfile but I get the same result.
Any help would be appreciated.
Thanks

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
