### ISSUE TITLE
how to support the Chinese words while editing the project?

### ISSUE THREAD

**Issue by sin-zx** [sharelatex/sharelatex-docker-image#37]
when i input the Chinese words and compile,they didn't display in the pdf.
@jpallen @henryoswald

**Comment by songjinghe** [comment]
maybe you should use xelatex (which originally support UTF8 characters) to compile your source. or use ctex package when using pdflatex to compile

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
