### ISSUE TITLE
SSL using Let's Encrypt 

### ISSUE THREAD

**Issue by theced7** [sharelatex/sharelatex-docker-image#38]
Hi,

I'm running Sharelatex on an AWS EC2 instance next to an Apache2 server which allows https using a "Let's Encrypt" certificate. 

I am not very experienced with Nginx and even less so with docker. Under my circumstances, what's the easiest way to get a secure connection to Sharelatex? 

Also, I'm sorry if that's not the right place to ask that question..

**Comment by ahxxm** [comment]
check [this](https://github.com/sharelatex/sharelatex/wiki/HTTPS-reverse-proxy-using-Nginx)

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
