### ISSUE TITLE
nomenclature doesn't work

### ISSUE THREAD

**Issue by featheryjam2** [sharelatex/sharelatex-docker-image#40]
I tried using the example given at the sharelatex website: https://www.sharelatex.com/learn/Nomenclatures

And the nomenclature section just prints blank.

**Comment by featheryjam2** [comment]
Anyone?  It seems to work on the actual sharelatex website.  I hope sharelatex haven't abandoned their "open source" version.

**Comment by gozzilli** [comment]
Same issue here. Please provide guidance.

**Comment by featheryjam2** [comment]
Their website version has been working for years so not sure why they haven't given this functionality to the open source version.  For what it's worth I gave up on this working and wrote my thesis in overleaf.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
