### ISSUE TITLE
Server doesn't answer

### ISSUE THREAD

**Issue by lukaspj** [sharelatex/sharelatex-docker-image#42]
I pulled the docker images for ShareLaTeX, docker and redis. I ran docker and redis like this:

```
sudo docker run --name sl-mongo -d mongo --net=host
sudo docker run --name sl-redis -d redis --net=host
```

And then when I ran ShareLaTeX docker image as given on the wiki:

```
docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --name=sharelatex \
  sharelatex/sharelatex
```

It seems to run without any issues, but then when I try to connect with http://host:5000 through my browser (where host is some ip-address, in my case http://192.81.221.40:5000/ it simply gives a time-out error.

It's probably me doing something wrong, but I can't figure out exactly what I'm doing wrong.

**Comment by msdayton** [comment]
Did you ever resolve this issue?

**Comment by lukaspj** [comment]
Nope, but I suspect that the server was simply too weak to handle the image. Couldn't afford upgrading it at the time to test it 😊

**Comment by msdayton** [comment]
I can get something to work if I follow the instructions from here:
https://hub.docker.com/r/tiagoboldt/sharelatex-docker/

I cant get the server (container) to respond to localhost:5000 if I follow the instructions from here:
https://github.com/sharelatex/sharelatex/wiki/Production-Installation-Instructions

the container exits after 2 minute of being up.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
