### ISSUE TITLE
Nginx Proxy to a path other than /

### ISSUE THREAD

**Issue by kastork** [sharelatex/sharelatex-docker-image#44]
Been trying to use the container behind nginx proxy.

Describes the case where sharelatex resides at the root path of the server.  It seems like some redirects assume that sharelatex is sitting at the root of the server, even when proxied according to

https://github.com/sharelatex/sharelatex/wiki/HTTPS-reverse-proxy-using-Nginx

I'm not using the SSL part of the config.  I've set up configs to include a path:

```
siteUrl : 'http://pogy.ern.nps.edu/latex'
behindProxy: true
apis:
    web:
       url: "http://localhost:3000/latex"
```

but the first visit to
    http://pogy.ern.nps.edu/latex
ends me up at
    http://pogy.ern.nps.edu/login
instead of 
    http://pogy.ern.nps.edu/latex/login

I don't see any obvious way to handle this in the Nginx config (but I'm no nginx master), and the available configs for sharelatex don't seem to give any other places to state the path.

Any clue?

**Comment by henryoswald** [comment]
Hi,

I don't think it is possible to run under a subpath at the moment.

**Comment by kastork** [comment]
I came to the same conclusion...

Would it be a feature request on sharelatex itself then?

**Comment by henryoswald** [comment]
its been requested somewhere already, its unlikely to get any development time if im being honest. Sorry about that.
