### ISSUE TITLE
add shell-escape in comunity edition

### ISSUE THREAD

**Issue by metal3d** [sharelatex/sharelatex-docker-image#45]
Hello

Is there a way to tell pdflatex to use -shel-escape options ? I tried to change the LatexCompiler options in source but, even if I restart container, the option won't be use (using minted says that the option is not set)

Thanks

**Comment by vagnum08** [comment]
Hi, 

I also had this problem with minted. I tried changing the _pdflatexCommand in LatexRunner.js and it worked.

Security wise is not the best solution, but if you really want to add shell escape to pdflatex you can do the following.

Enter into the running ShareLatex container using:

``` bash
 docker exec -it CONTAINER_NAME bash
```

Then using an editor, let's say vi, and edit `/var/www/sharelatex/clsi/app/js/LatexRunner.js`
Go to line `66` and change the `_pdflatexCommand` from

``` javascript
_pdflatexCommand: function(mainFile) {
return LatexRunner._latexmkBaseCommand.concat(["-pdf", "-e", "$pdflatex='pdflatex -synctex=1 -interaction=batchmode %O %S'", Path.join("$COMPILE_DIR", mainFile)]);
  }
```

to

``` javascript
_pdflatexCommand: function(mainFile) {
return LatexRunner._latexmkBaseCommand.concat(["-pdf", "-e", "$pdflatex='pdflatex -synctex=1 -shell-escape -interaction=batchmode %O %S'", Path.join("$COMPILE_DIR", mainFile)]);
}
```

Then exit from the container and restart it.

Similarly you can add -shell-escape to any other compiler by changing the corresponding function.

Hope this helps.
Cheers

**Comment by metal3d** [comment]
No news... ?

@vagnum08 that's what I did, it works - so I overrided the docker image to do this. But really, the community version *should* add this option

**Comment by Gibbus2** [comment]
This is still not fixed..? LatexRunner.js have changed so I don't think I can use the fix suggested by @vagnum08...

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
