### ISSUE TITLE
upload binary files bigger than 2 MB

### ISSUE THREAD

**Issue by fradelg** [sharelatex/sharelatex-docker-image#5]
It seems that the current configuration of nginx does not allow to upload binary files such as images or PDF. A solution could be to add the following line to nginx.conf to increase the maximum allowed upload size:

`client_max_body_size 8m;`

Take a look at this commit:

https://github.com/punkt2/sharelatex-docker-image/commit/906a414c92068f4cde17214c8c3fb9c5b076fbae

**Comment by tiendv** [comment]
hi fradelg, Could you tell me, now how could i config this if I've installed ?

**Comment by songjinghe** [comment]
@tiendv 
seems you are new to docker?(same with me)

## STEP 1

start sharelatex docker containner, you can find instructions in [README](https://github.com/sharelatex/sharelatex-docker-image), make sure you can access [http://localhost:5000](http://localhost:5000) ,if you're using the default option~

## STEP 2

run following command in terminal(I'm in ubuntu 14.04.3)

```
sudo docker exec -it sharelatex /bin/bash
```

now you're put into the root terminal of the containner. 

## STEP 3

edit the file `/etc/nginx/nginx.conf` with any available text editor

```
vi /etc/nginx/nginx.conf
```

and add `client_max_body_size 20m;` in the `http{` block, just like below:

```
http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 20m;   # <--- insert here, with any size you want~
        # server_tokens off;
```

then save and exit, and press CTRL-D to exit the docker terminal

## STEP 4

run

```
sudo docker ps
```

to get the current running containner ID(22dabd5c5292,for example)

## STEP 5

run

```
sudo docker commit 22dabd5c5292 sharelatex:mySharelatex
```

to commit your changes to a new image called `mySharelatex`,so you can find it with `sudo docker images`

## STEP 6

stop the original image/containner with `sudo docker stop sharelatex` and run the new one you just build:

```
sudo docker run -d -v ~/sharelatex_data:/var/lib/sharelatex -p 5000:80 --name=mySharelatex sharelatex:mySharelatex
```

now you can upload file as large as 20MB! enjoy~

**Comment by tiendv** [comment]
@songjinghe  , that true, I'm newbie in docker,  Thank you very much for your help ;)

**Comment by fradelg** [comment]
Thanks @songjinghe for the detailed explanation!

I think that STEP 5  and 6 can be replaced by a simple

`sudo docker restart mySharelatex`

However, changes will be lost if the container is destroyed later.

**Comment by henryoswald** [comment]
i've upped this to 50mb with 5c74504ce7757995ed13d20bb7e0c8a4158cfae6

**Comment by georgekamel** [comment]
Hello, I'd be really grateful if you could also increase the max project size from 5MB to 50MB as well, or make it so that it can be configured.
