### ISSUE TITLE
Missing dependency and db file

### ISSUE THREAD

**Issue by ghost** [sharelatex/sharelatex-docker-image#52]
I think that there is a missing dependency on the OS - sqlite. I installed docker, mongo etc on a fresh Ubuntu 16.04 and got the following error:

`*** Killing all processes...
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
chown: cannot access ‘/var/lib/sharelatex/data/db.sqlite’: No such file or directory
*** /etc/my_init.d/00_make_sharelatex_data_dirs.sh failed with status 1`

Even after installing sqlite this error would appear. I created an empty file in the right location and restarted and it worked.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
