### ISSUE TITLE
Fedora version and docker-compose

### ISSUE THREAD

**Issue by d2xdt2** [sharelatex/sharelatex-docker-image#57]
Using phusion is very bloated and tries to be a VM which defeats the purpose of Docker. Also it is not possible to debug with `docker run -ti --rm sharelatex  bash` because an init script takes over, which makes Docker harder to use rather than easier.

There are many bugs in this repo, e.g. `98_check_db_access.sh` is never executed.

**Question**

If I make a Fedora based version with `docker-compose.yml` which would make the wiki page obsolete about installing, configuring, and running. Would you then make it upstream?

The following repo is an example made for v0.0.2, so I would make it general purpose if you will make it upsteam.

https://github.com/dtu-compute/docker-sharelatex-fedora

**Comment by henryoswald** [comment]
Hi,

sorry I don't quite follow how it would make the wiki page obsolete? Our recommend install process is already using our docker compose file. If you have improvements i am always open to them.

**Comment by mserranom** [comment]
Closing this, we'll continue using Phusion as base container.
