### ISSUE TITLE
Glossaries not working

### ISSUE THREAD

**Issue by frecar** [sharelatex/sharelatex-docker-image#6]
Hi, I got the installation up and running, but using glossaries as I do on sharelatex.com does not work.

Are there any packages I have to install, or something else I need to configure? 

I have runned the `docker exec sharelatex tlmgr install scheme-full` command already.

Thanks!

**Comment by unusual-thoughts** [comment]
I'm getting the same issue here as well.
The minimal glossary example [provided on the sharelatex wiki](https://www.sharelatex.com/project/new/template?zipUrl=/project/533b1563d7244a2b31115400/download/zip&templateName=Glosary&compiler=pdflatex) works fine on sharelatex.com but inside my docker image it doesn't produce any errors, but doesn't show the glossary (and no mention in table of contents)

 On sharelatex.com the following temporary files are created

```
acn file
acr file
alg file
aux file
chktex file
glg file
glo file
gls file
ist file
log file
pdf file
synctex.gz file
toc file
```

While on the docker image:

```
acn file
aux file
glo file
ist file
log file
pdf file
synctex.gz file
toc file
```

It's missing the `.acr`, `.alg`, `.chktex`,  `.glg`, `.gls` files.

In the log files, the difference is that on sharelatex.com, near the end is

```
] (/compile/output.gls) [3

] (/compile/output.acr) [4

] (/compile/output.aux) ) 
```

On the docker image:

```
]
No file output.gls.
[3

]
No file output.acr.
[4

]
```

**Comment by ccremer** [comment]
I made it work, though the compiler takes longer (it runs twice or more):

```
\usepackage{glossaries}
\makenoidxglossaries
%This could be in a separate file and imported using \input:
\newacronym{arc}{ARC}{Adaptive Replacement Cache}

\begin{document}
\printnoidxglossary[type=\acronymtype,numberedsection=autolabel]
\end{document}
```

**Comment by pitasi** [comment]
Same problem here.
In the log I can see:
```
No file output.gls.
No file output.acr.
```
As @unusual-thoughts already pointed out.

`\makenoidxglossaries` is not working for me (can't find the command), is there any other workaround?

**Comment by unusual-thoughts** [comment]
My workaround is to include a custom `latexmkrc` file as per the [latexmk docs](http://mirror.ctan.org/support/latexmk/example_rcfiles/glossary_latexmkrc) in the root of each project that uses glossaries/acronyms containing:
```
add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
sub makeglo2gls {
    system("makeindex -s '$_[0]'.ist -t '$_[0]'.glg -o '$_[0]'.gls '$_[0]'.glo");
}

add_cus_dep('acn', 'acr', 0, 'makeacn2acr');
sub makeacn2acr {
    system("makeindex -s \"$_[0].ist\" -t \"$_[0].alg\" -o \"$_[0].acr\" \"$_[0].acn\"");
}
```
It should probably be installed into the system which is probably what they are doing on sharelatex.com
According to the `latexmk` [docs](http://mirror.ctan.org/support/latexmk/latexmk.txt), this should be:
```
1) The system RC file, if it exists.
   On a UNIX system, latexmk searches for following places for its system  RC  file,  in  the
   following order, and reads the first it finds:
   "/opt/local/share/latexmk/LatexMk",
   "/usr/local/share/latexmk/LatexMk",
   "/usr/local/lib/latexmk/LatexMk",
   "/opt/local/share/latexmk/latexmkrc",
   "/usr/local/share/latexmk/latexmkrc",
   "/usr/local/lib/latexmk/latexmkrc"
2) The  user's  RC  file,  "$HOME/.latexmkrc"
3) The RC file in the current working directory.  This file can be named  either  "latexmkrc"
or ".latexmkrc", and the first of these to be found is used, if any.
4) Any RC file(s) specified on the command line with the -r option.
```

**Comment by pitasi** [comment]
Worked like a charm.
I created the file `.latexmkrc` in the project root and used the code you posted.

Thank you so much for fixing this!

**Comment by joaoquintas** [comment]
This solution seems to work for me also! 

I share with you how I tested this workaround:

> **pre-conditions:**
> - main.tex in project root folder (with the acronym list declarations)
> - multiple latex files in multiple folders (use the acronyms declared in main.tex)
> - compiled an initial list of acronyms
> - acronyms list correctly displayed in document (\usepackage[acronym,toc,nonumberlist] {glossaries} ... \makeglossaries ... \printglossary[type=\acronymtype])

> **test1**:
> - add new acronym without clearing cache files
> - compiled using LaTex compiler
> 
> **test1 expected result:**
> - new acronym added to the list.
> 
> **test1 outcome**:
> passed

> **test2**:
> - add new acronym and cleared cache files
> - compiled using LaTex compiler
> 
> **test2 expected result:**
> - new acronym added to the list.
> 
> **test2 outcome**:
> passed

**Comment by petersipos** [comment]
@unusual-thoughts Thanks a lot! It works :)

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
