### ISSUE TITLE
Error on account activation

### ISSUE THREAD

**Issue by JanoschDeurer** [sharelatex/sharelatex-docker-image#63]
I installed sharelatex with the docker-image and got mail working. If I add a new user in the admin panel a mail with the password reset link is send as it should be. However, when users try to set their passwords, they get the following error:

> Your activation token has expired, you will need to get another one sent to you.

This happens immediately after sending the mail and not as described in the admin backend after one week.

**Comment by zhaozhi0505** [comment]
Exactly the same problem. Waiting for a fix.

**Comment by balkian** [comment]
Same here. Login with the created password works, tho.

These errors might be related: 

    "/var/www/sharelatex/web/public/minjs/libs/angular.min.js.map" failed (2: No such file or directory), client: 138.4.3.246, server: _, request: "GET /minjs/libs/angular.min.js.map HTTP/1.1", host: 


    114#0: *1034 upstream prematurely closed connection while reading response header from upstream, client: <IP>, server: _, request: "POST /user/password/set HTTP/1.1", upstream: "http://127.0.0.1:3000/user/password/set"

**Comment by zhaozhi0505** [comment]
Creating admin accounts from terminal works. But I cannot create admin accounts for everyone.
An alternative way, for the moment, is to create normal users from terminal with docker command line. But I don't know how. 

@balkian Do you know how to create normal user account from command line?

**Comment by balkian** [comment]
@zhaozhi0505 try to log in with the user. In my case it works, even after getting that error.

**Comment by zhaozhi0505** [comment]
@balkian Yes it works! So it looks like just the message problem. Thanks!

**Comment by JanoschDeurer** [comment]
@balkian That works for me too, thanks.

**Comment by Gizmoomzig** [comment]
I am having the same issue with the docker image but login still works despite the error. Is there a way to fix this?

**Comment by zhaozhi0505** [comment]
This problem is really annoying because every time I have to tell the user to ignore that message. How can we fix it? @henryoswald

**Comment by henryoswald** [comment]
we are working on a new system at the moment which will improve this flow.

**Comment by JanoschDeurer** [comment]
Seems like this is a general problem, not just one of the docker image, just stumbled over this:
[https://github.com/sharelatex/web-sharelatex/issues/392](url)

**Comment by ghost** [comment]
Same problem here. ~~I even get the welcome e-mail, but the pass reset is not working.~~
Is there a workaround for this?
This makes a new installation of sharelatex unusable.

**Comment by jlazerus** [comment]
👍

**Comment by zhaozhi0505** [comment]
I just upgrade the container to version 0.6.1. This bug is fixed. We can close this issue.

**Comment by mserranom** [comment]
Closed as per @zhaozhi0505  comment
