### ISSUE TITLE
Still having issues with special fonts

### ISSUE THREAD

**Issue by jazzdd86** [sharelatex/sharelatex-docker-image#64]
Hi,
this error exists for a long time, and I fixed it in one of my pull requests, but it was incorporated again into newer docker images.

If I am using for example
```
\RequirePackage[clock]{ifsym}
\Interval %timer symbol
```
it exits withh error that font does not exist.

A simple chown will get rid of that issue:
```
chown www-data:www-data /var/www/
```

**Comment by henryoswald** [comment]
hmmm stange, i have added https://github.com/sharelatex/sharelatex-docker-image/commit/4283bde9c00b42990787557b239a847b2ed3a089 in for you. How do you insert the font?

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
