### ISSUE TITLE
Protected Mongo breaks edition

### ISSUE THREAD

**Issue by metal3d** [sharelatex/sharelatex-docker-image#65]
I spent a long time to understand why #59 appears for me and looking at logs I just discovered why.

Actually, I tried to start ShareLatex on an OpenShift cluster (OSE - local cloud). OpenShift provides a persistent Mongo template that needs to set user and password to mongodb. 

So that, if we provide "mongo://user:password@mongodb/sharelatex" to mongo url env var for Sharelatex, everything works excepting loading document in editor. See https://github.com/sharelatex/sharelatex-docker-image/issues/59#issuecomment-273453119:

```json
{"name":"documentupdater","hostname":"sharelatex-1-y7xo3","pid":153,"level":50,"err":{"message":"auth failed","name":"MongoError","stack":"MongoError: auth failed\n  at Object.toError (/var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/utils.js:110:11)\n  at /var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/auth/mongodb_cr.js:34:33\n  at /var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/db.js:1670:9\n  at Server.Base._callHandler (/var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)\n  at /var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:472:18\n  at [object Object].MongoReply.parseBody (/var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)\n  at [object Object].<anonymous> (/var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)\n  at [object Object].emit (events.js:95:17)\n  at [object Object].<anonymous> (/var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)\n  at [object Object].emit (events.js:98:17)\n  at Socket.<anonymous> (/var/www/sharelatex/document-updater/node_modules/mongojs/node_modules/mongodb/lib/mongodb/connection/connection.js:384:22)\n  at Socket.emit (events.js:95:17)\n  at Socket.<anonymous> (_stream_readable.js:765:14)\n  at Socket.emit (events.js:92:17)\n  at emitReadable_ (_stream_readable.js:427:10)\n  at emitReadable (_stream_readable.js:423:5)\n  at readableAddChunk (_stream_readable.js:166:9)\n  at Socket.Readable.push (_stream_readable.js:128:10)\n  at TCP.onread (net.js:529:21)\n","ok":0,"errmsg":"auth failed","code":18},"msg":"request errored","time":"2017-01-18T11:42:20.598Z","v":0}
```

So I recreated a mongo docker container without any authentication, and then ShareLatex can now open documents in editor.

That means that document updater want to connect to mongo without any auth, or to something else that the provided **authorized** database (sharelatex in my example).

**Comment by henryoswald** [comment]
Hmmm have you tried restarting the docupdater, all apps use the same connection string and same driver. I assume you have not touched the docupdater in anyway?

**Comment by metal3d** [comment]
Hi @henryoswald,

at first: Thanks for your reply and for your great work

I haven't changed anything in docker, sources, or something else. I tried maybe 8 or 9 times to recreate the entire docker container stack.

You can try to launch your provided docker-compose.yml using that mongo image instead to reproduce the bug:
centos/mongodb-32-centos7
 => https://hub.docker.com/r/centos/mongodb-32-centos7/ 

This is the image base to create mongo container on openshift

EDIT: note that you MUST set user, password and admin password as env var for that mongo image

BTW: To use sharelatex on openshift, we need to break security to be able to let sharelatex container to start with "root" user inside. That is the reason why openshift provides others images where default user inside is not "root". At this time, I need to deactivate that protection to use your image, and because that bug, mongo container also.

**Comment by pugetc** [comment]
hi @metal3d , have you managed to deploy ShareLatex on OpenShift without breaking security? i need to do the same... thanks.

**Comment by dennxs** [comment]
Hi @metal3d @pugetc ,
is there any workaround for this issue?
I got same behavior when trying to run sharelatex inside google kubernetes engine.

Thanks in advance.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
