### ISSUE TITLE
Public projects are not public

### ISSUE THREAD

**Issue by ralienpp** [sharelatex/sharelatex-docker-image#66]
When someone opens the URL of a public project, they're still prompted for their credentials. This is an issue in the `web` component, discussed here: https://github.com/sharelatex/web-sharelatex/issues/367

The solution is to edit a config file and restart Sharelatex, but that doesn't apply in the case of a Docker container. Ideally it should be an option specified in the Dockerfile.

What is the recommended way of dealing with it?

**Comment by casselt** [comment]
You need to set SHARELATEX_ALLOW_PUBLIC_ACCESS to true. This was not documented until three weeks ago, but now you'll find it [here](https://github.com/sharelatex/sharelatex/wiki/Configuring-ShareLaTeX).

**Comment by mserranom** [comment]
@casselt response is the way to go.
