### ISSUE TITLE
Integration with github no-pro server

### ISSUE THREAD

**Issue by devmessias** [sharelatex/sharelatex-docker-image#69]
Hi, the  no-pro version of sharelatex server has  integration with github? 

I'm running  the "docker-compose" behind  of  a proxy  and the sharelatex interface does not show anything about integration with github

**Comment by epifanio** [comment]
Same here, just built git maste on ubuntu 17.04. now running on localhost. There is no github integration :(

**Comment by fahu** [comment]
Same for me, is there any statement from the developers to that? Is there a way to get Github support working on self-hosted no-pro version?

**Comment by arruw** [comment]
+1

**Comment by lukas681** [comment]
+1

**Comment by X-G** [comment]
same for me

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
