### ISSUE TITLE
Fatal error when trying to create admin user.

### ISSUE THREAD

**Issue by ohcfe** [sharelatex/sharelatex-docker-image#7]
with mongod version 3.0.1 installed, and redis-server version 2.8.19 installed on the docker host, I get:

> # docker exec sharelatex /bin/bash -c "cd /var/www/sharelatex/web; grunt create-admin-user --email joe@example.com"
> Running "create-admin-user" task
> Fatal error: driver is incompatible with this server version

It looks like your image is not compatible with mongod 3.0.1 (the latest stable version).

Which version of mongo is recommended?
Can it be fixed to work with 3.0.1?

**Comment by ohcfe** [comment]
It works well with mongod 2.6.9

**Comment by ar-jan** [comment]
+1. Otherwise, it would be good to mention the version requirements in the instructions.

**Comment by mhriemers** [comment]
Go into `/var/www/sharelatex/web` and change the version of mongoose to `3.8.27` in your `package.json` and run `npm install`.

**Comment by henryoswald** [comment]
We have upgraded our drivers to use mongo 3 now, the next release next week will contain them.

**Comment by ohcfe** [comment]
Given that I am running on mongo 2.6.9 what is the procedure for upgrading the docker image and database without losing all the projects?

**Comment by henryoswald** [comment]
The new docker image will also work with mongo 2.x so you should have no problems.

**Comment by hugoliv** [comment]
This issue hasn't been fixed.

**Comment by henryoswald** [comment]
We still need to release a new container with this update, sorry about that. I hope todo it in September.

**Comment by leandroqm** [comment]
lpsq's comment solves the issue for now.
 "Go into /var/www/sharelatex/web and change the version of mongoose to 3.8.27 in your package.json and run npm install."
Thank you @ipsq .

**Comment by mhriemers** [comment]
@leandroqm No problem. Happy to help. 

@henryoswald What about an automated build from Dockerhub?

**Comment by leandroqm** [comment]
That is what I am using, @ipsq . :-)
I did what you said (docker exec -it DOCKER_ID bash
cd /var/www/sharelatex/web/
vi package.json
alter mongoose's version to 3.8.27
npm install), then it works!
Thank you once again.

**Comment by klerisson** [comment]
Got a new error after following the proposed fix:
Error: version not found: mongoose@3.8.27

**Comment by yamalight** [comment]
getting the same error with current sharelatex docker image and mongo v3.2.1.
works OK with mongo v2.6.x.

**Comment by ghost** [comment]
I got the same error with mongo v3.2.2, any solution?

**Comment by ohcfe** [comment]
Yes, it works using mongo version 2.6.9

**Comment by exislow** [comment]
When you fill fix this, guys? You mentioned here https://github.com/sharelatex/sharelatex/issues/403 mongo 3.x works with actual Docker image, but it doesn't!

This fix https://github.com/sharelatex/sharelatex-docker-image/issues/7#issuecomment-137227625 does not work for me:

```
root@418c59b33ac0:/var/lib/sharelatex/web# npm install
npm WARN package.json connect-redis@1.4.5 No repository field.
npm WARN package.json dateformat@1.0.4-1.2.3 No repository field.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> dtrace-provider@0.2.4 install /var/lib/sharelatex/web/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory `/var/lib/sharelatex/web/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider/build'
  SOLINK_MODULE(target) Release/obj.target/DTraceProviderBindings.node
  SOLINK_MODULE(target) Release/obj.target/DTraceProviderBindings.node: Finished
  COPY Release/DTraceProviderBindings.node
  TOUCH Release/obj.target/libusdt.stamp
make: Leaving directory `/var/lib/sharelatex/web/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider/build'

> kerberos@0.0.9 install /var/lib/sharelatex/web/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/lib/sharelatex/web/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/var/lib/sharelatex/web/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.22 install /var/lib/sharelatex/web/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/lib/sharelatex/web/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/var/lib/sharelatex/web/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
settings-sharelatex@1.0.0 node_modules/settings-sharelatex
└── coffee-script@1.6.0

metrics-sharelatex@1.0.0 node_modules/metrics-sharelatex
└── coffee-script@1.6.0

soa-req-id@1.0.0 node_modules/soa-req-id
├── coffee-script@1.4.0
└── mocha@1.8.2 (growl@1.7.0, commander@0.6.1, diff@1.0.2, mkdirp@0.3.3, debug@2.2.0, ms@0.3.0, jade@0.26.3)

logger-sharelatex@1.0.0 node_modules/logger-sharelatex
├── coffee-script@1.4.0
└── bunyan@0.16.8 (dtrace-provider@0.2.4)

translations-sharelatex@0.1.0 node_modules/translations-sharelatex
├── coffee-script@1.10.0
├── onesky@0.1.6 (request@2.40.0)
└── i18next@1.7.10 (json5@0.2.0, cookies@0.6.1)

mongoose@3.8.27 node_modules/mongoose
├── regexp-clone@0.0.1
├── sliced@0.0.5
├── muri@1.1.0
├── hooks@0.2.1
├── mpath@0.1.1
├── mpromise@0.4.3
├── ms@0.1.0
├── mquery@1.4.0 (debug@0.7.4, bluebird@2.3.2)
└── mongodb@1.4.32 (readable-stream@2.0.6, kerberos@0.0.9, bson@0.2.22)
```

**Comment by henryoswald** [comment]
0.3 should have this fixed
