### ISSUE TITLE
Cannot mount volume  over  var/www/sharelatex/web

### ISSUE THREAD

**Issue by devmessias** [sharelatex/sharelatex-docker-image#70]
```yml
version: '2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            - mongo
            - redis
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex #ok
            - ~/sharelatex_web:/var/www/sharelatex/web #fail
``

**Comment by henryoswald** [comment]
/var/www/sharelatex/web is where the app lives so mounting it there would break.

**Comment by devmessias** [comment]
Thank you. I aim to create an integration with git repositories.  For this reason I would to like  mount the volume /var/www/sharelatex/web,  so I could edit the code from my host machine.

**Comment by henryoswald** [comment]
that isn't really going to be possible the way ShareLaTeX is built, it doesn't use the filesytem like git, its all in the DB

**Comment by devmessias** [comment]
Uhn, I'm confused. I couldn't  use the files inside "var/lib/data/compiles" for the git repositories ?

**Comment by henryoswald** [comment]
you can use those but its one way only. You cant change the file system and it show up in ShareLaTeX

**Comment by devmessias** [comment]
I could use the FileSystemImportManager to create files on database...Is it a bad idea?

**Comment by henryoswald** [comment]
its not a great idea, that could easily break with future changes.

**Comment by devmessias** [comment]
Ok, I need find a solution for this. I'll think more about this problem.

Thanks for your advice and the sharelatex.
