### ISSUE TITLE
Backing up scripts

### ISSUE THREAD

**Issue by nicola** [sharelatex/sharelatex-docker-image#71]
Is it possible for the team to come up with a very little script that would backup the current local sharelatex and one that could re-store it?

That would be awesome!

**Comment by mlopezantequera** [comment]
If it helps, this is my backup script that I run daily with a cronjob.

You could replace the "cp" with a rsync directory, I just copy to a network mount.

```
#!/usr/bin/env bash

#
# This script is to be run in the sharelatex server.
#

# Variables
dstdir=/my/nas/mount/dir

# Copy the mongodb and the data directory to tmpdir
tmpdir='/tmp/sharelatex_backup'
rm -rf "$tmpdir"
mkdir "$tmpdir"
cd "$tmpdir"
mongodump
cp /var/lib/sharelatex ./ -rv

# Compress the tmpdir into a tarfile
tarfile=/tmp/sharelatex_bk_$(date +%Y%m%d_%H%M%S).tar.gz
tar -czf "$tarfile" "$tmpdir"

# Copy to the destination directory
cp --no-preserve=mode "$tarfile" "$dstdir" -v
rm "$tarfile"

# Keep only the 14 most recent backups
ls -1tr "$dstdir"/sharelatex_bk_*.tar.gz | head -n -14 | xargs -d '\n' rm -f --
```

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
