### ISSUE TITLE
Please update quickstart guide 

### ISSUE THREAD

**Issue by gdisneyleugers** [sharelatex/sharelatex-docker-image#72]
When I attempted to run grunt user:create_admin. I got:

Running "user:create-admin" task
Set UV_THREADPOOL_SIZE=16
{"name":"default-sharelatex","hostname":"b50c48ef51bd","pid":59,"level":30,"feature":"ratelimiter","msg":"creating redis client","time":"2017-04-14T09:36:47.511Z","v":0}
{"name":"default-sharelatex","hostname":"b50c48ef51bd","pid":59,"level":40,"msg":"Email transport and/or parameters not defined. No emails will be sent.","time":"2017-04-14T09:36:47.567Z","v":0}
Fatal error: Redis connection to dockerhost:6379 failed - connect ECONNREFUSED

Please update document to use:
docker run -d -P -p 80:80 -v ~/sharelatex_data:/var/lib/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --link mongo:mongo --link redis:redis --name sharelatex sharelatex/sharelatex

This does not work:
$ docker run -d \
  -v ~/sharelatex_data:/var/lib/sharelatex \
  -p 5000:80 \
  --name=sharelatex \
  sharelatex/sharelatex

**Comment by epifanio** [comment]
It is much easier to just run `docker-compose up` i the main repository. It satisfy the mongo and redis dependencies. No git-hub integration, no track-changes, no comments ... :(

**Comment by mserranom** [comment]
This has been fixed already
