### ISSUE TITLE
Cached/maked files not found by pdflatex. \tikzexternalize[mode=list and make]  not working. 

### ISSUE THREAD

**Issue by Tobias2** [sharelatex/sharelatex-docker-image#73]
There is a great method to incremental compile with multi-core-cpu   if you have many complex plots generated with `tikz`.  
But I have a problem to get this working on Sharelatex.

Automated work flow:
------------------
 1. automatically generate individual tasks for each tikz-picture in a makefile (`\tikzexternalize[mode=list and make]`)
 2. compile tikz-pictures simultaneously  using 8-core cpu !!! (`make -j8 -f %B.makefile`)
 3. automatically insert tikz-pictures as pdf-files in second run of pdflatex (`\usetikzlibrary{external}`) 

Here is a simplified MWE that should work on our local machine. 
[ExternalListAndMake.zip](https://github.com/sharelatex/sharelatex-docker-image/files/922988/ExternalListAndMake.zip)

Run with ` latexmk  -pdf   main.tex `

    %%% file named main.tex %%%
    \documentclass{article}
    \usepackage{tikz,pgfplots}
    %\pgfplotsset{compat=1.14}
    \usetikzlibrary{external}
    \tikzexternalize[mode=list and make]

    %%%  please create file latexmkrc manually %%%
    % \begin{filecontents}{latexmkrc} 
    % $pdflatex='pdflatex --shell-escape -synctex=1 -interaction=batchmode %O %S;  make -f %B.makefile; pdflatex --shell-escape -synctex=1 -interaction=batchmode %O %S';
    % \end{filecontents}

    \begin{document}
        \tikzsetnextfilename{myPlot}
        \begin{tikzpicture}
            \begin{axis}
                \addplot coordinates {(1,1) (2,2) (3,3)};
            \end{axis}
        \end{tikzpicture} 
    \end{document} 

Observation in Sharelatex
--------
I want to get the example working on Sharelatex. If you test on your own docker, you have to activate `-shell-escape ` in `/var/www/sharelatex/clsi/app/js/LatexRunner.js` with respect to [https://github.com/sharelatex/sharelatex-docker-image/issues/45](https://github.com/sharelatex/sharelatex-docker-image/issues/45)

 1. The makefile is generated by `tikz-external` as expected. 
 2. The `make`-command works as expected. The file **myPlot.pdf is generated** and can be found in cache beside the log-files. 
 3. In the second run of pdflatex, the **myPlot.pdf is NOT inserted** in the main-file. 

Problem
-------
In the second run of pdflatex, it looks like **myPlot.pdf does not exist**. The warning is:

    Package `tikz` Warning: Some images are not up-to-date and need to be generated.

And actually: if I download myPlot.pdf and upload it again so that it is a regular part of the project and not only a cached file, **everything works fine**!

Question
--------
**How can I tell sharelatex to see the cached files in the second run of pdflatex?**

Are there any options, flags, ... in any config-file** deep inside the sharelatex-code that could help? Maybe have to give access privileges to any processes?
 
*I would be really happy if you could help me. Furthermore, the solution could result in a great feature to other users for quite fast compiling on a fast multi-core server?!*

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
