### ISSUE TITLE
docker-compose UnicodeEncodeError

### ISSUE THREAD

**Issue by ChristianPe** [sharelatex/sharelatex-docker-image#76]
Hi there,

every time I try to install sharelatex using docker, I run into the same error:

> Traceback (most recent call last):
>   File "logging/__init__.py", line 861, in emit
>   File "logging/__init__.py", line 734, in format
>   File "compose/cli/formatter.py", line 50, in format
>   File "logging/__init__.py", line 469, in format
> UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 110: ordinal not in range(128)
> Logged from file main.py, line 80

If I just try to pull the image I get a similar error:

> failed to register layer: Error processing tar file(exit status 1): symlink spanish.alias /usr/lib/aspell/espa�ol.alias: invalid or incomplete multibyte or wide character

The error is the same on docker 1.12 and 1.13 and docker-compose 1.8 and 1.13. The system is Ubuntu 16.04 running on zfs. 
Im not having the issue with the sharelatex image from jrandall, but since jrandall didnt update for a year, I wanted to use the official one. 
I tried to change the locales (in the compose file as well) with 

> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> export LANGUAGE=en_US.UTF-8

but it did not change anything. 
Does somebody has a clue why this is happening?

Thanks in advance

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
