### ISSUE TITLE
Latest/v0.6.3 docker hub images uses depreciated 2016 texlive

### ISSUE THREAD

**Issue by dtu-compute** [sharelatex/sharelatex-docker-image#77]
Texlive 2017 got released 4th of June 2017 and it seams as latest/v0.6.3 is built with the 2016 version. The result of this is that `tlmgr` doesn't work because Texlive is very quick in shutting down deprecated repos.

**Comment by iainbryson** [comment]
Further details:

When we build the Dockerfile-base, we get:

```
[root@enote-devel2 sharelatex-docker-image]# docker build -f Dockerfile-base .
Sending build context to Docker daemon 252.4 kB
Step 1/17 : FROM phusion/baseimage:0.9.16
.
.
.
Step 13/17 : ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2016/bin/x86_64-linux/
 ---> Using cache
 ---> 88647182f605
Step 14/17 : RUN tlmgr install latexmk
 ---> Running in aca3e12a0106
/bin/sh: 1: tlmgr: not found
The command '/bin/sh -c tlmgr install latexmk' returned a non-zero code: 127
[root@enote-devel2 sharelatex-docker-image]# 
```

Note that `texlive` is now install to the `2017` directory, while the path is `2016`. Changing it to 2017 fixes the issue.

**Comment by magic-lantern** [comment]
I don't have the ability to close this bug, but this problem has clearly been resolved as the same thing has occurred again but now with version 2017 on the image vs only 2018 being available for texlive. The same problem is happening again, path is outdated and texlive is outdated.

If anyone with ability to close this bug, please do so.

**Comment by jdleesmiller** [comment]
Thanks for the update. We will look into the new TL 2018 release.
