### ISSUE TITLE
migrations do not work: TypeError: db.collection is not a function

### ISSUE THREAD

**Issue by detorto** [sharelatex/sharelatex-docker-image#87]
Just tried to upgrade from 0.2.0 to latest. 

After 
`docker pull & docker run ... sharelatex/sharelatex:latest  `
old projects did no open.

In logs I found next record: 

```
Warning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://mongo/sharelatex
/var/www/sharelatex/node_modules/mongodb/lib/mongo_client.js:797
          throw err;
   
TypeError: db.collection is not a function

```

The solution is to downgrade sharelatex mongojs package:
attach to docker container shell and run
cd /var/www/sharelatex/; npm install mongodb@2.2.33 --save

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
