### ISSUE TITLE
Issue with Building a Docker Image then Running ShareLatex

### ISSUE THREAD

**Issue by ExtremelySeriousChicken** [sharelatex/sharelatex-docker-image#89]
I have been toying around the docker-image and built the docker image locally, then run Sharelatex based on locally built image. However, when I run Sharelatex, localhost does not work. Does the image that the current sharelatex is using different from the master's branch?

**Comment by magic-lantern** [comment]
Do you have more details on what is going wrong?

I'm not a maintainer nor developer of ShareLatex, but have also built the docker image locally and then use docker-campose up to start the sharelatex image along with mongo and redis.

If you kept the default name, and run this:

`docker exec -it sharelatex bash`

You then are inside a shell in the docker container. You can then look at the various logs to see more details on any errors you may be getting. Most of the relevant logs appear to be in /var/log/sharelatex

By looking at my log files I discovered that the document-updater service didn't build right the first time, so I ran 

```
cd /var/www/sharelatex/document-updater
npm start
```

and now on subsequent stop/start cycles the docker image works great.

**Comment by mickaelbaron** [comment]
Hi @ExtremelySeriousChicken,

I suppose a problem on the versions of node and npm. Can you check the node version please?

`docker exec -it sharelatex /bin/bash node -v`

The _sharelatex:sharelatex-base_ Docker image from DockerHub repository is an old image. From this Docker image, node 0.10.48 is installed, it's not sufficient to build all modules of Sharelatex...

Mickael

**Comment by mickaelbaron** [comment]
Hi @magic-lantern,

I've the same problem on you 

> the document-updater service didn't build right the first time 

Have you an idea to fix this problem during the Docker image building?

Mickael

**Comment by mickaelbaron** [comment]
Hi @magic-lantern,

I found why the _document-updater_ service didn't build right. I think Grundfile.coffee file is missing at the root of the project. I've opened an issue about it => https://github.com/sharelatex/document-updater-sharelatex/issues/60

Mickael

**Comment by magic-lantern** [comment]
@mickaelbaron Thanks for the research and suggested fix. I was able to do a manual work around but had no idea why it wasn't working. Your issue sounds like it might be the culprit.

**Comment by mickaelbaron** [comment]
@magic-lantern 

When i'm using the Docker image from Dockerhub (_sharelatex/sharelatex:latest_) _Gruntfile.coffee_ file is present into the _document_updater_ service. Very strange...

My question is the following, what is the Git repository used to build official sharelatex Docker image? In fact, in this Git repository https://github.com/sharelatex/document-updater-sharelatex, there is not _Gruntfile.coffee_ file.

Mickael

**Comment by mickaelbaron** [comment]
Hi,

I proposed you a fix to build Sharelatex Docker image. See my Git repository => https://github.com/mickaelbaron/sharelatex-docker-image

Moreover, i proposed a PR to fix the problem of missing Gruntfile.coffe => https://github.com/sharelatex/document-updater-sharelatex/pull/61

I hope it will be useful ;-)

Mickael

**Comment by magic-lantern** [comment]
Tanks @mickaelbaron - hopefully the project maintainers will accept your pull request and make a new version of the docker container that works. Until then, your branch appears to be a better source then  upstream.

**Comment by mserranom** [comment]
Closing,not relevant after latest in v2.x.
