### ISSUE TITLE
runit run files missing after container restart

### ISSUE THREAD

**Issue by peterlustig671** [sharelatex/sharelatex-docker-image#92]
## Problem

Starting the docker image the *first time* with `docker-compose up` everything works fine. After stopping the container and starting it again with `docker-compose start` I get an empty response when trying to connect to it and errors show up when attaching to the container (see Logs and errors). 

After removing the created containers manually or with `docker-compose down` and then recreating the containers with `docker-compose up`, everything works as expected again.

After stopping and started the container, the run files, which should be at  `/etc/service/*/run` are gone.

## Install type

Installed via `docker-compose.yml`

## Version

Docker version 18.05.0-ce, build f150324

## Logs and errors

sharelatex    | runsv real-time-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv clsi-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv notifications-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv errorlogs: fatal: unable to start ./run: file does not exist
sharelatex    | runsv web-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv contacts-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv docstore-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv filestore-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv tags-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv track-changes-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv spelling-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv nginx: fatal: unable to start ./run: file does not exist
sharelatex    | runsv chat-sharelatex: fatal: unable to start ./run: file does not exist
sharelatex    | runsv document-updater-sharelatex: fatal: unable to start ./run: file does not exist

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
