### ISSUE TITLE
base image (phusion/baseimage:0.9.16) still depends on ubuntu 14.04

### ISSUE THREAD

**Issue by fsalvi** [sharelatex/sharelatex-docker-image#95]
Hello,

Is it on purpose that sharelatex docker image is still based on ubuntu 14.04 ? 18.04 was released a few weeks ago and 14.04 will not be maintained anymore next April...

Is there any plan to upgrade the base image to a more recent version or some dependencies cause problems ?

**Comment by jdleesmiller** [comment]
Thanks for getting in touch. Yes --- we will be updating the image, but since 14.04 still has a year before it is EOL, we are not planning to do it urgently.

**Comment by fsalvi** [comment]
Just a reminder, Ubuntu 14.04 will reach its End of Life on April 30, 2019
